### ISSUE TITLE
Disregard of character encoding

### ISSUE THREAD

**Issue by Kissaki** [davetcc/hugojoomla#10]
It seems like the export does not respect the utf-8 character encoding. After conversion the md files contain invalid characters.

My website is in `utf-8`, my database default collation is `utf8_general_ci`, although most content tables seem to be collation `utf8mb4_unicode_ci`.

**Comment by davetcc** [comment]
I need to think about how this can be handled. Maybe a config option to indicate the MySQL driver needs to use a different char set.

**Comment by davetcc** [comment]
I don't really have a database installed that's in the right format, or any content that is likely to fail conversion. If you wanted to take a look at the code and try a local build the connectionProperties component in src/main/resources/hugoJoomla.xml is where JDBC connection is prepared.
