### ISSUE TITLE
Prepackaged version unavailable

### ISSUE THREAD

**Issue by misolietavec** [davetcc/hugojoomla#7]
You write in documentation:

"You can use the packaged version that is available from the releases page. Building from source is not required."

There is no releases page. I do not like to install the big maven suite only to try hugojoomla...

Michal

**Comment by davetcc** [comment]
Hi there,

Please try the following page that has a zip file available:

https://github.com/davetcc/hugojoomla/releases

Let me know if that doesnt work for you.

Many thanks,
Dave

**Comment by misolietavec** [comment]
Hi, Dave,

Dňa 24.12.2016 19:54 Dave Cherry napísal(a):
> Hi there,
> 
> Please try the following page that has a zip file available:
> 
> https://github.com/davetcc/hugojoomla/releases
> 
> Let me know if that doesnt work for you.

I think, somewhere in documentation shoud be mentioned the link to this 
page.
I downloaded, unzipped, runned. Got an exception:

2016-12-24 21:12:36 ERROR JoomlaHugoConverter:120 - Did not complete 
conversion
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad 
SQL grammar [select C.id as id, U.username as username, C.created as 
created, C.introtext as intro,        C.`fulltext` as full, D.path as 
path, C.title as title, C.alias as alias,
        C.images as images, c.state as state, D.alias as catAlias
from jos_content C, jos_users U, jos_categories D
where C.created_by = U.id
   and D.id = C.catid
   and D.path <> 'uncategorised'
]; nested exception is 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown 
column 'c.state' in 'field list'

===============================
Maybe, you forgot that in UNIX-like systems the column names are case 
sensitive?
(C.state instead of c.state)

I am using debian stable/testing, and output of "java -version" is

openjdk version "1.8.0_111"

Michal

**Comment by davetcc** [comment]
Hi Michael

Agreed, I've only ever run the tool on Win10. I'll run it in the bash
environment and try it.

I'll see if I can get an hour later today / tomorrow after the festivities
to try it!

Thanks
Dave

**Comment by misolietavec** [comment]
Hi, Dave,
   I can confirm that after making change in file  JoomlaHugoConverter.java, line 81:

c.state as state  change to: C.state as state

the utility is working. Please make this change in sources and recompile the binary release.

Michal

**Comment by davetcc** [comment]
Many thanks and apologies for not getting around to it sooner. I'll be able
to patch it in tomorrow when I get back to the office.

Glad it worked for you BTW.

**Comment by davetcc** [comment]
Thanks again for the patch, it is applied on master and a new release version built. If you came across any significant issues during conversion let me know and I can try and make the library more general purpose.
